### ISSUE TITLE
"*:port" doesn't work as catchall bind host for -L forwards in 2.0.0 & produces invalid autossh call

### ISSUE THREAD

**Issue by foosel** [jnovack/autossh#27]
Hi there!

First of all thank you very much for the work you've put into this, I've been using your autossh image for a long time now and greatly appreciate how easy you've made everything.

I have my docker containers deployed with watchtower enabled and recently got updated to version 2.0.0 by that. That caused a bit of confusion at first, but I finally was able to figure out the stuff I needed to change after actually comparing the README with my compose file 😅

I wanted to bind the forwarded port in the docker container to `*:19999` and thus set `SSH_TUNNEL_PORT=*:19999` as written in the docs:

![image](https://user-images.githubusercontent.com/83657/104131025-38d92a00-5374-11eb-95e6-f03bf519493d.png)

However that results in an invalid command line which autossh complains about, e.g. `-L 127.0.0.1:*:19999:127.0.0.1:19999` which obviously is wrong.

So I dug into the entrypoint script and noticed that I should actually be using an undocumented env var called `SSH_BIND_IP` for this. Setting that to `0.0.0.0` achieved what I wanted:

``` yaml
  autossh:
    image: jnovack/autossh
    container_name: autossh
    environment:
      - SSH_REMOTE_USER=someuser
      - SSH_REMOTE_HOST=somehost
      - SSH_REMOTE_PORT=22
      - SSH_BIND_IP=0.0.0.0
      - SSH_TUNNEL_PORT=19999
      - SSH_TARGET_HOST=127.0.0.1
      - SSH_TARGET_PORT=19999
      - SSH_MODE=-L
```

I this a documentation bug (wrong reference to `*:port` and missing docs for `SSH_BIND_IP`) or a bug in the implementation (missing parsing)? If it is a documentation bug, I'd be happy to send a PR your way to fix it.
