### ISSUE TITLE
Quirky to mount a volume that contains the id_rsa and known_hosts

### ISSUE THREAD

**Issue by Megamannen** [jnovack/autossh#35]
I suggest that the destination mounting point should be something like /config/id_rsa instead of /id_rsa so we can mount a volume to /config that contains both id_rsa and known_hosts

You can of course work around this by mounting the volume to config and set SSH_KEY_FILE and SSH_KNOWN_HOSTS_FILE.

**Comment by jnovack** [comment]
This would be a breaking change to existing setups.  Not worth breaking when variables can solve it. 

As you mentioned, this solves it.

```yaml
volumes:
  - ./config:/config
environment:
  - SSH_KEY_FILE=/config/id_rsa
  - SSH_KNOWN_HOSTS_FILE=/config/known_hosts
```
